# Generated by Django 4.2.2 on 2023-06-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
