# Generated by Django 4.2.2 on 2023-06-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
